name: PlatformIO CI

on: [push]


# see e.g. https://cgrotz.github.io/2020-08-24-esp32_ci_cd_part2/

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    
    # Prepare environment
      - uses: actions/checkout@main
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio





    # Build ESP code
      - name: Build PlatformIO Project ESP32
        working-directory: ./ESP32
        run: | 
          pio system info
          pio run --environment esp32 
    #      pio run --environment esp32s3usbotg
    #      pio run --environment esp32-speedcrafter
             
        
        
        
        
        
        
        
    # copy files to dir
      - name: Copy files to packing dir
        run: | 
          copy ${{ github.workspace }}/ESP32/.pio/build/esp32/firmware.bin  ${{ github.workspace }}/Helper/bins/esp32
          copy ${{ github.workspace }}/ESP32/.pio/build/esp32/bootloader.bin  ${{ github.workspace }}/Helper/bins/esp32
          copy ${{ github.workspace }}/ESP32/.pio/build/esp32/partitions.bin  ${{ github.workspace }}/Helper/bins/esp32
          copy ${{ github.workspace }}/ESP32/.pio/build/esp32s3usbotg/firmware.bin  ${{ github.workspace }}/Helper/bins/esp32s3
          copy ${{ github.workspace }}/ESP32/.pio/build/esp32s3usbotg/bootloader.bin  ${{ github.workspace }}/Helper/bins/esp32s3
          copy ${{ github.workspace }}/ESP32/.pio/build/esp32s3usbotg/partitions.bin  ${{ github.workspace }}/Helper/bins/esp32s3
          copy ${{ github.workspace }}/ESP32/.pio/build/esp32-speedcrafter/firmware.bin  ${{ github.workspace }}/Helper/bins/esp32_speedcrafter_PCB_V1p4
          copy ${{ github.workspace }}/ESP32/.pio/build/esp32-speedcrafter/bootloader.bin  ${{ github.workspace }}/Helper/bins/esp32_speedcrafter_PCB_V1p4
          copy ${{ github.workspace }}/ESP32/.pio/build/esp32-speedcrafter/partitions.bin  ${{ github.workspace }}/Helper/bins/esp32_speedcrafter_PCB_V1p4
    
    
    
    
    
    
    
    # copy files to dir
      - name: List files in dir
        run: | 
          dir ${{ github.workspace }}/Helper/bins/esp32
    
    
    
    
    

    # zip plugin binaries
      - name: ZIP files
        run: | 
          7z a ${{ github.workspace }}/Helper/zip/esp32.zip ${{ github.workspace }}/Helper/bins/esp32/
          7z a ${{ github.workspace }}/Helper/zip/esp32s3.zip ${{ github.workspace }}/Helper/bins/esp32s3/
          7z a ${{ github.workspace }}/Helper/zip/esp32_speedcrafter.zip ${{ github.workspace }}/Helper/bins/esp32_speedcrafter_PCB_V1p4/
    #      7z a ./Helper/zip/esp32.zip @./Helper/zip/filelist_esp32.txt
    #      7z a ./Helper/zip/esp32s3.zip @Helper/zip/filelist_esp32s3.txt
    #      7z a./Helper/zip/esp32_speedcrafter.zip @Helper/zip/filelist_esp32_speedcrafter.txt
       



       
    # Publish as build artifact
      - name: Attach artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware_esp32
          path: | 
            ./Helper/zip/esp32.zip
            ./Helper/zip/esp32s3.zip
            ./Helper/zip/esp32_speedcrafter.zip
        
        
        
